---
title: "In-class Demo of Dashboard"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: scroll
    css: styles.css
    #vs. fill
    #fill leaves you with a fixed amount of space
    #theme: spacelab
    
---

```{r setup, include=FALSE}
library(flexdashboard)
library(tidyverse)
#install.packages("plotly")
library(plotly)
library(rio)
library(here)
library(colorblindr)
```

```{r}
data <- import(here("reg_data.csv"))

my_colors <- c("darkblue","darkmagenta", "chartreuse", "cyan","tomato")
```

Demographics
==========


Column {data-width=600}
-----------------------------------------------------------------------

### Education

```{r}

data %>% 
  ggplot(aes(edu)) + 
  geom_bar(aes(fill = edu), show.legend = FALSE) + 
  labs(x = "education level", y = "number of people", fill = "Education Level") + coord_flip() + theme(axis.title.y=element_blank()) + scale_fill_manual(values = my_colors)


# ggplot(df, aes(x=x, y=y))+
#   geom_point() +
#   theme(axis.text.x=element_blank(), #remove x axis labels
#         axis.ticks.x=element_blank(), #remove x axis ticks
#         axis.text.y=element_blank(),  #remove y axis labels
#         axis.ticks.y=element_blank()  #remove y axis ticks
#         )

#cvd_grid(g)
```


### Insulin Therapy

```{r}

data %>% 
  ggplot(aes(insulin)) + 
  geom_bar(aes(fill = insulin), show.legend = FALSE) + 
  labs(x = "Gender", y = "number of people", fill = "insulin") + theme(axis.title.x=element_blank()) + scale_fill_manual(values = my_colors)

```


Column {data-width=600}
-----------------------------------------------------------------------




### Gender  {data-padding=10}

```{r}

data %>% 
  ggplot(aes(gender)) + 
  geom_bar(aes(fill = gender), show.legend = FALSE) + 
  labs(x = "Gender", y = "number of people", fill = "Gender") + theme(axis.title.x=element_blank()) +  scale_fill_manual(values = my_colors)

```

### Place

```{r}
data %>% 
  ggplot(aes(rural_urban)) + 
  geom_bar(aes(fill = rural_urban), show.legend = FALSE) + 
  labs(x = "Rural/Urban", y = "number of people", fill = "Rural/Urban") + theme(axis.title.x=element_blank()) +  scale_fill_manual(values = my_colors)

```


Stats!
===========

```{r include=FALSE}
data <- data %>%
  mutate(
    across(
      # ^means begins with. 0-9 are the possible numbers and {1,2} means it 
      # could be one or two digits
      matches("^resources_[0-9]{1,2}$"), 
# need to ask Sara about what the period inside parens indicates
      ~ ifelse(is.na(.), 0, 1)))

```

```{r include=FALSE}
# data <- survey2 %>% 
# mutate(resource_sum = rowSums(resources_1,resources_2,resources_3, resources_4, resources_5, resources_6,resources_7, resources_8, resources_9, resources_10, resources_11, resources_12, resources_13, resources_14, resources_15,resources_16, resources_17, resources_18, resources_19 ,resources_20, resources_21))

data$resources_1 <- as.numeric(data$resources_1)
data$resources_2 <- as.numeric(data$resources_2)
data$resources_3 <- as.numeric(data$resources_3)
data$resources_4 <- as.numeric(data$resources_4)
data$resources_5 <- as.numeric(data$resources_1)
data$resources_6 <- as.numeric(data$resources_1)
data$resources_7 <- as.numeric(data$resources_1)
data$resources_8 <- as.numeric(data$resources_1)
data$resources_9 <- as.numeric(data$resources_1)
data$resources_10 <- as.numeric(data$resources_1)
data$resources_11 <- as.numeric(data$resources_1)
data$resources_12 <- as.numeric(data$resources_1)
data$resources_13 <- as.numeric(data$resources_1)
data$resources_14 <- as.numeric(data$resources_1)
data$resources_15 <- as.numeric(data$resources_1)
data$resources_16 <- as.numeric(data$resources_1)
data$resources_17 <- as.numeric(data$resources_1)
data$resources_18 <- as.numeric(data$resources_1)
data$resources_19 <- as.numeric(data$resources_1)
data$resources_20 <- as.numeric(data$resources_1)
data$resources_21 <- as.numeric(data$resources_1)



#sub <- data %>% 
  #select(resources_1:resources_21)
  



 data$res_sum = data %>% 
  select(resources_1:resources_21) %>% 
   rowSums(na.rm=T)
#  
# 

# data_mod <- sub %>%
# mutate(sum_res = rowSums(.))
# print(data_mod)
# 
# new <- data_mod %>% 
#   select(sum_res)

# data_mod <- data %>%
# mutate(sum_of_rows = rowSums(resources_1,resources_2,resources_3, resources_4, resources_5, resources_6,resources_7, resources_8, resources_9, resources_10, resources_11, resources_12, resources_13, resources_14, resources_15,resources_16, resources_17, resources_18, resources_19 ,resources_20, resources_21))

#dat <- cbind(data, new)

```

```{r}

#dat$dds_means = as.numeric(dat$dds_means)
#dat$sum_res = as.numeric(dat$sum_res)
#dat$sum_res = as.integer(dat$sum_res)
 #g <- 
data %>% 
  ggplot(aes(res_sum, des_score)) + 
  geom_point(aes(size = chai_means),color = "purple3") +           scale_color_manual(values = my_colors)+ 
  theme_classic() + 
  theme(axis.line = element_line(colour = "darkmagenta", 
       linewidth = 2, linetype = "solid")) +  scale_fill_manual(values = my_colors) + 
  xlim("1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13") +
  labs(x = "Number of Resources Used", y = "Diabetes Empowerment")

#p  + theme( axis.line = element_line(colour = "darkorchid", 
                      #linewidth = 2, linetype = "solid"))

#Want to make this so that when you hover over the points it shows you the names of the resources the person uses

#ggsave("g.png")
```

### Location  {data-padding=10}

```{r}

data %>% 
  ggplot(aes(rural_urban)) + 
  geom_bar(aes(fill = rural_urban), show.legend = FALSE) + 
  labs(x = "Rural/Urban", y = "number of people", fill = "Rural/Urban") + theme(axis.title.x=element_blank())

```


--------



### Chart D 

```{r}
#{.storyboard} removed this for now
int <- import(here("text_data.xlsx"))

dat <- left_join(data, int)

library(tidytext)

dat <- dat %>% 
unnest_tokens(word, lows)

dat %>% 
anti_join(stop_words) %>% 
  filter(word != "low",word !="yeah",word != "ago",word != "feel", word !="feeling", word != "lows", word != "describe", word != "super", word != "sugar", word != "straight", word != "start", word != "dexcom", word != "feels", word != "feelings", word != "extreme", word != "gonna", word != "guys") %>% 
count(word, sort = TRUE) %>% 
  mutate(word = reorder(word, n)) %>% # make y-axis ordered by n
  slice(1:20) %>% # select only the first 15 rows
  ggplot(aes(n, word)) +
  theme_minimal() +
    geom_col(fill = "darkorchid")+ theme(panel.grid.major.x = element_line(color = "grey",size = 0.25, linetype = 1), panel.grid = element_blank()) + labs( x = "Count", y = "Word", Title = "Word frequencies in posts", subtitle = "Top 20 words displayed", caption = "From first 5 interviews")


```

```{r}
library(wordcloud2) 

 
int2 <- int %>% 
unnest_tokens(word, lows) %>% 
  select(word, part_id) |>
  anti_join(stop_words)



#letterCloud( frequency_dataframe, word = "LOW", color="white", backgroundColor="deepskyblue")

#letterCloud( demoFreq, word = "PEACE", color="white", backgroundColor="pink")

#view(demoFreq)

#wordcloud2(data=demoFreq, size=1.6)


frequency_dataframe = int2 %>% count(word) %>% arrange(desc(n))

letterCloud( frequency_dataframe, word = "LOW", color="brown", backgroundColor= "green")

```


Start Here
=================================

-----------
### Chart E

```{r echo=FALSE}
#letterCloud( frequency_dataframe, word = "LOW", color="black", backgroundColor="deepskyblue")


draft <- wordcloud2(data=frequency_dataframe, size=1.6)

ggsave("draft.png")

draft
```

### Chart F

### Chart G
-------------
Demo Tab
========================
### Chart H


# Questions

* x axis on resource number
* Is it possible to publish word cloud onto website?
* plotly - hover values different than axis values?